library("GET")
library("spatstat.model")
library("ggplot2")
X <- spruces
print(X)
pdf("spruces.pdf")
plot(X)
dev.off()
k <- Kest(X)
print(k)
pdf("sprucesK.pdf")
plot(k)
dev.off()
env <- envelope(X, nsim=1999, savefuns=TRUE,simulate=expression(runifpoint(ex=X)),verbose=FALSE)
print(env)
pdf("sprucesEnv.pdf")
plot(env)
dev.off()
res <- global_envelope_test(env)
print(res)
pdf("sprucesEnvTest.pdf")
plot(res)
dev.off()
